### ISSUE TITLE
关于图片发送失败的bug

### ISSUE THREAD

**Issue by licat233** [TangSengDaoDao/TangSengDaoDaoAndroid#1]
聊天界面，图片发送失败，但图片消息体的状态不会变成发送失败状态，一直处于发送中状态。

**Comment by No8blackball** [comment]
更新到最新代码试下

**Comment by licat233** [comment]
> 更新到最新代码试下

已更新，bug依旧，log打印:
```log
{"msg":"上传文件失败！","status":400}
```
但view视图并没有做出失败的响应，img消息体依旧显示发送中状态，只有退出了当前聊天窗口，回到聊天列表，img消息体才会更新为发送失败状态。

**Comment by licat233** [comment]
看了源代码，主要逻辑代码在chat/base/msgitem/WKChatBaseProvider.kt内setMsgTimeAndStatus函数:
当发送消息失败时，该方法接收到的mMsg.status状态始终为0，即WKSendMsgResult.send_loading状态，才会出现图片发送失败了，一直在转圈圈，不会提示失败。
当我在592行加入以下代码后，能正常显示发送失败状态
```kotlin
if (mMsg.status == WKSendMsgResult.send_loading && mMsg.remoteExtra.needUpload != 1) mMsg.status = WKSendMsgResult.send_fail
  ```
  就是不知道该解决方法是否可靠，是否有副作用，请作者帮忙看一下

**Comment by No8blackball** [comment]
把sdk更新到1.0.8再试下

**Comment by licat233** [comment]
> 把sdk更新到1.0.8再试下

可以了，原来是sdk的bug啊
