### ISSUE TITLE
安卓新手 消息记录加载问题

### ISSUE THREAD

**Issue by xwg-github** [TangSengDaoDao/TangSengDaoDaoAndroid#12]
聊天对话框中的历史消息，每次加载白屏一段时间在渲染出来

**Comment by No8blackball** [comment]
显示loading表示客户端不满足查询条件。可能的原因：
1、参数原因。如果每次打开页面就是传入的oldseq=0，sdk默认就会同步一次频道消息
2、当前会话查询到的总条数不满足limit参数，sdk就会同步频道消息
3、当前会话的最后一屏幕存在重试消息，导致同步下来的消息数量并不是查询的总数量。比如：查询20条，同步接口返回20条，但是其中2条是重试导致的重复消息，sdk就只会保存18条，不满足查询结果，这样每次打开聊天就会同步一次

综上所述，只要当前聊天超过一页数据时就不会出现这种情况

**Comment by xwg-github** [comment]
现在局域网是断开的情况下，应该是同步不了信息，会话展开还是先白一会才显示。你们的 demo 就不会

**Comment by xwg-github** [comment]
消息记录上下滑动时卡顿是什么原因呢？

**Comment by xwg-github** [comment]
已解决。正式包与调试包的问题导致
