### ISSUE TITLE
输入框高度异常bug

### ISSUE THREAD

**Issue by anlanemo** [TangSengDaoDao/TangSengDaoDaoAndroid#2]
1、全新安装app并用gitee登录，打开群聊第一次点击输入框时，输入框无法被顶上去！只有弹出一次键盘，第二次点击输入框才会正常显示！
2、安卓13在群聊界面，使APP变为split-screen（分屏）,freeform（自由窗口），然后恢复正常！再点击输入框，输入框被键盘覆盖一样无法正常显示！
3、横竖屏切换后输入框高度也会异常，在AndroidManifest改变com.chat.uikit.chat.ChatActivity的android:screenOrientation="fullSensor"后可测试！
4、手动调整输入法键盘高度后，输入框高度无法立即跟随改变！

当聊天窗口大小发生变化(例如浮窗、横竖屏切换)后，app会重新计键盘高度，再次点击输入框时输入框高度就错乱了！

**Comment by No8blackball** [comment]
最新的Demo已优化键盘高度变化自适应问题了

**Comment by anlanemo** [comment]
感谢通知😊。我安卓14上测试了下，键盘适配的效果很好很贴合和TG一样，安卓9输入框上弹少有延迟但已经很不错了，其他随键盘高度自适应调整都正常。
