### ISSUE TITLE
当程序处于后台的时候 它就不会接收信息

### ISSUE THREAD

**Issue by yuyue2013** [TangSengDaoDao/TangSengDaoDaoAndroid#5]
当我切换出程序后 程序应该是运行在后台的 这个时候它就不会接收信息， 这个要怎么处理？

**Comment by yuyue2013** [comment]
我的系统是HarmonyOS 4.0.0

**Comment by tangtaoit** [comment]
需要配置推送，查看配置文件： https://tsdaodao.com/dev/backend/fullconfig.html
